version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: punto-venta
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: punto-venta-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/punto-venta
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: angel
    ports:
      - "9898:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
